### ISSUE TITLE
Draft workflow for synchronization mechanism

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/DroneDB#181]
- [ ] Research and document push/pull workflow and test cases

**Comment by HeDo88TH** [comment]
**Extended documentation:**

Source DDB:

```
[
    "pippo.jpg",
    "pluto.jpg",
    "minnie.jpg",
    "gambadilegno.jpg",
    "1.jpg",
    "pics/2.jpg",
    "pics/3.jpg"
]
```

Destination DDB:

```
[
    "pippo.jpg",
    "pluto.jpg",
    "minnie.jpg",
    "minnie2.jpg",
    "topolino.jpg",
    "1.jpg",
    "2.jpg",
    "images/2.jpg",
    "images/4.jpg"
]
```

Delta:

```
{
    "add": [
        "topolino.jpg",
        "minnie2.jpg",
        "images/4.jpg"
    ],
    "copy": [
        ["pics/2.jpg", "images/2.jpg"],
	["pics/2.jpg", "2.jpg"]
    ],
    "remove": [
        "gambadilegno.jpg",
        "pics/3.jpg",
	"pics/2.jpg",
    ]
}
```

The first set of actions specifies what files need to be added, the second one what files need to be copied and the last one what files to be removed.
The actions need to be applied in this strict order: add, copy, remove.
With this structure we can handle multiple files with same content (using hash) but different paths. In the above example, the files `pics/2.jpg` and `2.jpg` are the same file but in different locations. This algorithm is able to minimize the "add" actions in order to lower the bandwidth usage in case of network sync.

**The diff algorithm is the following:**

![delta](https://user-images.githubusercontent.com/7868983/106649314-ae11d680-6591-11eb-8a93-cb8c502b8c3f.png)

**Comment by pierotofy** [comment]
Problem:

```
<filename> <hash>

source
======
a.txt 0xaa
b.txt 0xbb

destination
===========
a.txt 0xcc (modified)
b.txt 0xdd (new file named b.txt)
c.txt 0xbb (b.txt has been renamed)

sequence of operations:
=======================
add: a.txt
add: b.txt
copy: b.txt --> c.txt (oops! c.txt is 0xdd, not 0xbb)
```

I think there needs to be some sort of "temporary" state where added files (perhaps with some special file prefix, like `a.txt.tmp`) are kept temporarily until  the copy operation can be performed (or vice-versa). This could help with the need with a transactional state too (what if I press CTRL+C during sync?)

Also, probably an optimization, but there are cases where we could do a rename instead of a copy (or wild idea, we could create hard-links instead of a copy).

How do we handle directories?

**Comment by pierotofy** [comment]
Can you include the other test cases you've examined?

**Comment by HeDo88TH** [comment]
Here it is the updated diff workflow
![diff](https://user-images.githubusercontent.com/7868983/107237697-4e02b080-6a27-11eb-8a89-cf496e4b1f87.png)

**Comment by HeDo88TH** [comment]
@pierotofy  Here they are `ddb push` and `ddb pull` workflows

![ddb push](https://user-images.githubusercontent.com/7868983/110979986-a3ebb080-8365-11eb-8134-9a338866483f.png)
![ddb pull](https://user-images.githubusercontent.com/7868983/110980002-a64e0a80-8365-11eb-97b0-efd821923dd0.png)

**Comment by pierotofy** [comment]
This looks good.

I wonder, since the logic of performing deletes, renames and adds needs to be done on the client (with `ddb pull`) it might make a lot of sense to implement this logic as a ddb command / API! This way Registry's `Apply dataset changes` are really just the same logic?

E.g. you could have a command that takes:

 * Output of delta (JSON)
 * A target DroneDB directory path 
 * A source directory (from where to find the files, e.g. the temp directory in Registry). 

I'm not considering issues with the system abstraction however, so perhaps two separate code bases need to be written.

**Comment by HeDo88TH** [comment]
I thought about it carefully and the logic will have to be implemented on both ddb and registry (using filesystem abstraction). 

What Registry will reuse from ddb is the diff logic but the code to apply that diff is not portable due to the filesystem abstraction. The delta command is what will be used to get the diff. The rest of the logic will be inside the push and pull commands.

**Comment by pierotofy** [comment]
Makes sense.
