### ISSUE TITLE
ddb clone causes inconsistent modified time values

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/DroneDB#224]
ddb clone causes every cloned file to have a different `mtime` than the one recorded on the index.

This is turn causes other commands such as `ddb status` to take forever, because sha256 hashes have to be computed.

I think a clone (and pull) should make sure that the mtime values in the index are reflected onto the file system (or vice-versa).

**Comment by HeDo88TH** [comment]
This issue is dependent on the client FS. Sometimes unzipping preserves files mtime but not all the times. 
The only ghetto-style solution is to manually set the mtime of the files after they are extracted.

**Comment by pierotofy** [comment]
I think it would be a reasonable solution. Most filesystems allow it.

**Comment by HeDo88TH** [comment]
I have performed extensive tests on this problem. It basically boils down to managing file storage (and caching) plus a problem in the client's unzip library.

The first problem is that we don't keep the mtime when we store the file on S3. Because the "Last Modified" date indicates when it was last modified on S3 (upload date). Not when it was last modified on FS.
The registry, when downloading files from the backend, does not know their actual mtime. Also, when zipping to clone, it updates the mtime to when the file was zipped.
During cloning, the unzip library does not set mtime. This way the mtime of the files is the time they were last unzipped.

We have more problems here and more ways to fix or mitigate them.
My proposal is that we can set the mtime of files when downloading from S3 based on the stored mtime of ddb. When the client clones the repository, ddb should preserve that mtime without modifying it.

What do you think of this @pierotofy?

**Comment by pierotofy** [comment]
Sounds good to me.
